SR = 44100
RECORDINGS_DIR = "data"
AVAILABLE_LANGUAGES = ["polish", "italian"]
CLASSES = ["HS", "PD"]
NUM_CLASSES = len(CLASSES)
RUN_DATASET_ANALYSIS = False
SUMMARY_PATH = "data/database_summary.xlsx"
PRINT_DB_INFO = False
SAVE_PLOTS = True
SHOW_PLOTS = False
COMPUTE_ADDITIONAL_FEATURES = False

CLASS_ENCODING = {"PD": 1, "HS": 0}
GENDER_ENCODING = {'K': 0, 'M': 1}
